//
//  ProgressInteractor.swift
//  iTobacWorker
//
//  Created by Nikolas on 07.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProgressBusinessLogic
{
  func doSomething(request: Progress.Something.Request)
}

protocol ProgressDataStore
{
  //var name: String { get set }
}

class ProgressInteractor: ProgressBusinessLogic, ProgressDataStore
{
  var presenter: ProgressPresentationLogic?
  var worker: ProgressWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Progress.Something.Request)
  {
    worker = ProgressWorker()
    worker?.doSomeWork()
    
    let response = Progress.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
