//
//  ProgressPresenter.swift
//  iTobacWorker
//
//  Created by Nikolas on 07.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProgressPresentationLogic
{
  func presentSomething(response: Progress.Something.Response)
}

class ProgressPresenter: ProgressPresentationLogic
{
  weak var viewController: ProgressDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Progress.Something.Response)
  {
    let viewModel = Progress.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
