//
//  AuthorizationInteractor.swift
//  iTobacWorker
//
//  Created by Nikolas on 14.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationBusinessLogic
{
}

protocol AuthorizationDataStore
{
    //var name: String { get set }
}

class AuthorizationInteractor: AuthorizationBusinessLogic
{
    var presenter: AuthorizationPresentationLogic?
    var worker: AuthorizationWorker?
  
}

extension AuthorizationInteractor:AuthorizationDataStore{
    //var name = ""
}
